server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/realms/cinelist/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/realms/cinelist
      registration:
        spring-with-test-scope:
          provider: keycloak
          client-id: auth-service-1
          client-secret: vUcAz4VSxznvLD9M5LERpbJfKavEfnyz
          authorization-grant-type: authorization_code
          scope: openid
