spring:
  application:
    name: apigateway

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: false

cloud:
  gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true