spring:
  main:
    lazy-initialization: true

  jpa:
    open-in-view: true

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true